### ISSUE TITLE
User password does not persist to state file

### ISSUE THREAD

**Issue by pasali** [DeviaVir/terraform-provider-gsuite#57] opened 2019-03-19 06:27 UTC
I am defining my `gsuite_user` like this 

```hcl
resource "gsuite_user" users {
  count = "${length(var.users)}"
  name {
    given_name = "${lookup(var.users[count.index], "first_name") }"
    family_name = "${lookup(var.users[count.index], "last_name") }"
  }

  password = "hashed_password"
  hash_function = "SHA-1"

  primary_email = "${lookup(var.users[count.index], "email") }"

}
```
on the first apply everything works like expected but if i apply again, terraform treat password like empty and set password to `hashed_password` like there is change.

Version:
    Terraform v0.11.11
        + provider.gsuite v0.1.15

**Comment by DeviaVir** [comment] 2019-03-19 09:33
Hi @pasali.
 
This is by design, the google API does not return which password is currently set, so we cannot compare those and thus do not save the password to the state file. It is recommended to set the password during creation so you can share that out (also set `change_password_next_login = true`), then after initial creation you set `password = ""` and `change_password_next_login = false`, from this point on the password is managed by the user and Google.

**Comment by pasali** [comment] 2019-03-19 12:21
I was doing something similiar what you suggested. I was using `ignore_changes` field for password. I was going to ask you to leave `password` field out of update action but you have already done it :)
Thanks for quick reply.

**Comment by DeviaVir** [comment] 2019-03-20 11:24
Contained in v0.1.17 :+1: 
closing.

**Closed by DeviaVir** 2019-03-20 11:24 UTC
Labels: question
