### ISSUE TITLE
Add members using a list doesn't 

### ISSUE THREAD

**Issue by LucianoAdonis** [DeviaVir/terraform-provider-gsuite#31] opened 2018-07-24 15:36 UTC
Well, I'm been trying to add members to a group using a list of users instead of using the attribute "members" for each user. I want a second opinion about how to manage the behavior of the provider handling the users with count and how to deal with other limits like quantity of users that can be created with this method.

My main looks something like this:
```
### GROUP ###

resource "gsuite_group" "viewer" {
  email       = "group@domain.com"
  name        = "group@domain.com"
  description = "View stuff"
}

### MEMBERS ###

resource "gsuite_group_members" "members" {
  group_email = "${gsuite_group.viewer.email}"
  count = "${length(var.users)}"
  depends_on = ["gsuite_group.viewer"]
  member {
    email = "${element(var.users, count.index)}"
  }

}
```

And the vars for that:
```
variable "users" {
  type = "list"
  default = [
    "user00@domain.com",
    "user01@domain.com",
    "user02@domain.com"
  ]
}
```

Let me explain the behavior of the provider processing a list with an example. Let's say that i want to use a list of 2 members using count for repeat the user creation. First creates the members resource [0] with user00, then creates a new members resource [1] with user01 and then destroy user00 (and the resource) and add him to the second one. Its no a problem when there are a few users, but when it comes to 11 users breaks, 10 its the limit (I can say that after a lot of testing).

And if its not clear for my lovely English, using for a list for creating members its more something like this:

```
group test [0] = user00

#Destroy [0] and members within it
group test [1] = user00, user01

#Destroy [1] and members within it
group test [2] = user00, user01, user02

#Destroy [2] and members within it
group test [3] = user00, user01, user02, user03
```

And then if you use "terraform apply"
```
-/+ group test [0]               
member.#:                 "4" => "1" (forces new resource)

-/+ group test [1]
member.#:                 "4" => "1" (forces new resource)

-/+ group test [2]
member.#:                 "4" => "1" (forces new resource)

-/+ group test [3]
member.#:                 "4" => "1" (forces new resource)
```

This scenario is avoidable using the intended way:

```

### TEAM MEMBERS ### 
resource "gsuite_group_members" "members" {  
  group_email = "${var.group_mail}"   
  
  member {    
    email = "user00@domain.com"    
    role = "MEMBER"  
  }   

  member {    
    email = "user01@domain.com"   
    role = "MEMBER"  
  }   

  member {    
    email = "user02@domain.com"    
    role = "MEMBER"  
  }   

  member {    
    email = "user03@domain.com"    
    role = "MEMBER"  
  }
}
```
And because the point of using the GSuite provider is to add at least 15 different users to different projects. It can be this way.

The workaround that i figure out for this was using 3 "gsuite_group_members" all of them pointing to one group. It kinda works for 15 users, using 3 groups with 5 each, but it breaks sometimes. But using lists means that it won't have the track of the added members, and starts to recreate them, and breaks (usually). Well this creation process is suppose to happens just one time. But still is like force the provider in a way that isn’t meant to (Or I least believe so).

And sometimes has problems with members of other domains.

**List of commons errors doing this:**
A list that that include the causes that I believe for each of this issues.

Memberkey notFound:
```
Error: Error applying plan:
2 error(s) occurred:
* gsuite_group_members.the_cooler_view_members[9]: 1 error(s) occurred:
* gsuite_group_members.the_cooler_view_members.9: Error updating memberships: Error deleting member: googleapi: Error 404: Resource Not Found: memberKey, notFound
```
* This happens when I use more than 4 mails (in a list) that doesn't belong to the domain.
* And for the same motive explain with the destroy/creations of users. 11+ Users.

Update users:
```
* gsuite_group_members.members[3]: 1 error(s) occurred:
* gsuite_group_members.members.3: Error updating memberships: Error deleting member: googleapi: Error 404: Resource Not Found: memberKey, notFound
* gsuite_group_members.members[4]: 1 error(s) occurred:
* gsuite_group_members.members.4: Error updating memberships: Error deleting member: googleapi: Error 412: Condition not met, conditionNotMet
```
* Same as Memberkey notFound, the process of recreate existent users destroy more than expected or no domain users are not find.

Update memberships
```
3 error(s) occurred:
 
* module.account.gsuite_group_members.latam_team_members[4]: 1 error(s) occurred:
 
* gsuite_group_members.latam_team_members.4: Error updating memberships: Error deleting member: googleapi: Error 404: Resource Not Found: memberKey, notFound
```
* Too much users.
* Sometimes happens with 2-4 users, but the "fix" y tried to apply like 3 times and it will create them or part of them. Something more like timing when destroying.
* The solution for 2-4 users doesn't work with +11 because shows that succeed but doesn't create them all.

Updating memberships ft. Condition not met:
```
Error: Error applying plan:
2 error(s) occurred:
* gsuite_group_members.members[5]: 1 error(s) occurred:
* gsuite_group_members.members.5: Error updating memberships: googleapi: Error 404: Resource Not Found: groupKey, notFound
* gsuite_group_members.members[0]: 1 error(s) occurred:
* gsuite_group_members.members.0: Error updating memberships: Error creating groupMember: googleapi: Error 412: Condition not met, conditionNotMet, userXX@domain.com
```
* It's similar to the other but happens when adding more than 4 users that doesn't belong to the domain and then complains about normal domain users.

I really appreciate any help you can provide.

**Comment by DeviaVir** [comment] 2018-12-21 13:38
Resource `gsuite_group_members` expects a list of members, not to be counted over, you can/should use `gsuite_group_member` for that. It's the cause of all of your issues.

example:
```
resource "gsuite_group_members" "admin_team_members" {
  group_email = "${gsuite_group.admin_team.email}"

  member {
    email = "test@test.com"
    role  = "OWNER"
  }

  member {
    email = "test1@test.com"
    role  = "MEMBER"
  }
}
```

I'll close this issue for now, let me know if there's other issues.

**Closed by DeviaVir** 2018-12-21 13:38 UTC
Labels: question
